### ISSUE TITLE
Handle `IamProvider` breaking change in rusoto

### ISSUE THREAD

**Issue by indiv0** [InQuicker/kaws#10]
Hello, just thought I should notify you that there's been a breaking change in rusoto (https://github.com/rusoto/rusoto/pull/435) which affects your project. Particularly, `IamProvider` has been renamed to `InstanceMetadataProvider`.

You'll need to change the references to `IamProvider` [here](https://github.com/InQuicker/kaws/blob/e1c5c92e8b96ae107bb932f401471b4e1f3a78a1/agent/src/decryption.rs) once you update to rusoto 0.20.0. :)

Although that being said it looks like you're still on rusoto 0.13.0, so this won't affect you if you choose to stay on that version.

**Comment by jimmycuadra** [comment]
Thanks for the heads up!

**Comment by matthewkmayer** [comment]
I think this has been tackled since `kaws` is on Rusoto 0.27.0. 😄
